apiVersion: v1
kind: Service
metadata:
  name: {{ include "datatorch.fullname" . }}-api
  labels:
    app: {{ include "datatorch.name" . }}-api
    {{- include "datatorch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      protocol: TCP
      targetPort: 4000
  selector:
    app: {{ include "datatorch.name" . }}-api
