apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datatorch.fullname" . }}-postgres
type: Opaque
data:
  username: {{ .Values.backend.database.username | default .Values.postgresql.postgresqlUsername | b64enc | quote}}
  password: {{ .Values.backend.database.password | default .Values.postgresql.postgresqlPassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "datatorch.fullname" . }}-license
type: Opaque
data:
    licenseEmail: {{ .Values.licenseEmail | b64enc | quote }}
    licenseKey: {{ .Values.licenseKey | b64enc | quote }}