apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "datatorch.fullname" . }}-tasks
  labels:
    app: {{ include "datatorch.name" . }}-tasks
    {{- include "datatorch.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.tasks.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "datatorch.name" . }}-tasks
      {{- include "datatorch.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "datatorch.name" . }}-tasks
        {{- include "datatorch.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: datatorch-tasks
          image: {{ .Values.tasks.image }}:{{ .Values.tasks.tag }}
          imagePullPolicy: Always
          env:
            - name: LOGGER_LEVEL
              value: {{ .Values.backend.logging }}
              # Database configuration
            - name: DATABASE_HOST
              value: {{ .Values.backend.database.host | default (printf "%s-postgresql" .Release.Name) | quote}}
            - name: DATABASE_NAME
              value: {{ .Values.backend.database.name | default .Values.postgresql.postgresqlDatabase | quote }}
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "datatorch.fullname" . }}-postgres
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "datatorch.fullname" . }}-postgres
                  key: password
            - name: DATABASE_PORT
              value: {{ .Values.backend.database.port | default .Values.postgresql.service.port | quote }}
            - name: DATABASE_SSL
              value: {{ .Values.backend.database.ssl |  default "false" | quote }}
              # Redis configuration
            - name: REDIS_HOST
              value: {{ .Values.backend.redis.host | default (printf "%s-redis-master" .Release.Name) | quote}}
            - name: REDIS_PORT
              value: {{ .Values.backend.redis.port | default .Values.redis.redisPort | quote}}
            - name: REDIS_PASSWORD
              value: {{ .Values.backend.redis.password | default .Values.redis.password | quote }}            
          {{- if .Values.api.resources }}
          resources: {{- toYaml .Values.tasks.resources | nindent 12 }}
          {{- end }}
        {{- if .Values.backend.extraContainers }}
        {{- toYaml .Values.backend.extraContainers | nindent 8 }}
        {{- end }}
      volumes:
        {{- if .Values.backend.extraVolumes }}
        {{- toYaml .Values.backend.extraVolumes | nindent 8 }}
        {{- end }}
      