apiVersion: v1
kind: Service
metadata:
  name: {{ include "datatorch.fullname" . }}-webclient
  labels:
    app: {{ include "datatorch.name" . }}-webclient
    {{- include "datatorch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webclient.service.type }}
  ports:
    - name: http
      port: {{ .Values.webclient.service.port }}
      protocol: TCP
      targetPort: 3000
  selector:
    app: {{ include "datatorch.name" . }}-webclient
