{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "datatorch.fullname" . }}-ingress
  labels:
    {{- include "datatorch.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /api
        backend:
          serviceName: {{ include "datatorch.fullname" . }}-api
          servicePort: http
      - path: /
        backend:
          serviceName: {{ include "datatorch.fullname" . }}-webclient
          servicePort: http
  {{- if .Values.ingress.extraRules }}
  {{- toYaml .Values.ingress.extraRules | nindent 2 }}
  {{- end }}

{{- end }}