apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "datatorch.fullname" . }}-webclient
  labels:
    app: {{ include "datatorch.name" . }}-webclient
    {{- include "datatorch.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.webclient.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "datatorch.name" . }}-webclient
      {{- include "datatorch.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "datatorch.name" . }}-webclient
        {{- include "datatorch.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: datatorch-webclient
          image: {{ .Values.webclient.image }}:{{ .Values.webclient.tag }}
          env:
            - name: API_FQDN
              value: {{ .Values.apiFQDN | quote }}
            - name: GTM
              value: {{ .Values.webclient.googleTagManager | default "" | quote }}
          ports:
            - containerPort: 3000
          {{- if .Values.api.resources }}
          resources: {{- toYaml .Values.tasks.resources | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 5

      imagePullSecrets:
        - name: regcred
